[tool.bandit]
exclude_dirs = [
    "docs",
    "tests"
]

[tool.black]
target-version = [
    'py37',
    'py38',
    'py39',
    'py310',
    'py311'
]

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
